# Generated by Django 4.2.1 on 2023-12-14 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0005_userprofile_email_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='verification_token',
        ),
    ]
