# Generated by Django 4.2.1 on 2023-12-14 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0007_userprofile_verification_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='verification_token',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
