# Generated by Django 4.2.1 on 2023-12-14 23:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0009_userprofile_salt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='salt',
        ),
    ]
