# Generated by Django 4.2.1 on 2023-12-16 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0013_alter_userprofile_two_factor_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('PREMIUM_USER', 'Premium User'), ('USER', 'User')], default='USER', max_length=15),
        ),
    ]
