# Generated by Django 4.2.1 on 2023-12-24 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pet_shop', '0016_blogpost_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='files',
        ),
    ]
